### ISSUE TITLE
Menu is not shown when main view is shorter than menu

### ISSUE THREAD

**Issue by kmswic** [edge1s/pipca#11]
1. Open the app. People component is open by default.
2. Menu is hidden behind a scrollbar (see screenshot)
   ![pipca](https://cloud.githubusercontent.com/assets/8117469/18030127/f081f6f0-6cab-11e6-9900-d64015deeac6.png)

**Expected behavior:**
Menu should be shown regardless of the contents of the main view

**Comment by piotros** [comment]
This bug is a little bit weird because it appears only after first app opening. After page refresh everything look as expected. I guess that this may be a problem with MDL.

**Comment by piotros** [comment]
I've created pull request #14 that contains upgraded version of vue-mdl in which this bug is fixed.
